name: "Setup Monitoring Environment"
description: "Setup environment de monitoring"

runs:
  using: "composite"
  steps:
    - name: Setup Environment
      shell: bash
      run: |
        # initialiser environment
        pip install -e .\[monitoring\]
