# version: '3.8'

# services:
#   nginx:
#     image: nginx:latest
#     container_name: nginx
#     ports:
#       - "80:80"
#       - "443:443"
#     networks:
#       - private_network
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#       - ./certs:/etc/nginx/certs
#     depends_on:
#       - app
#       - api

#   app:
#     image: your_app_image
#     container_name: app
#     networks:
#       - private_network
#     environment:
#       - FLASK_APP=app.py
#       - FLASK_ENV=production

#   api:
#     image: your_api_image
#     container_name: api
#     networks:
#       - private_network
#     environment:
#       - API_KEY=your_api_key

# networks:
#   private_network:
#     driver: bridge

# Remarque : Sans ports : Les services app et api ne sont accessibles que par d'autres services du réseau Docker (birdcleff_network).
version: '3'
services:
  app:
    image: birdcleff_app_image
    build:
      context: .
      dockerfile: Dockerfile.app
    # ports:
    #   - "5000:5000"
    depends_on:
      - api
    networks:
      - birdcleff_network

  api:
    image: birdcleff_api_image
    build:
      context: .
      dockerfile: Dockerfile.api
    # ports:
    #   - "8080:8080"
    networks:
      - birdcleff_network
    # ## avant ssl
    # nginx:
    #   image: birdcleff_nginx_image
    #   build:
    #     context: .
    #     dockerfile: Dockerfile.nginx
    #   ports:
    #     - "80:80"
    #   depends_on:
    #     - app
      # networks:
      #   - birdcleff_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - api
    networks:
      - birdcleff_network

networks:
  birdcleff_network:
    #external: true
    driver: bridge
