name: "Terraform Deploy"
description: "Deploie application + service sur azure"

inputs:
  AZURE_ENVIRONMENT:
    description: "Environment sur lequel deployer"
    required: true

runs:
  using: "composite"
  steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Deploy ${{ inputs.AZURE_ENVIRONMENT }}
        env:
          AZURE_ENVIRONMENT: ${{ inputs.AZURE_ENVIRONMENT }}
        run: |
          cd .cd
          terraform init
          terraform plan -var="environment=${AZURE_ENVIRONMENT}"
          # terraform apply -auto-approve
