name: "Terraform Deploy"
description: "Deploie application + service sur azure"

inputs:
  TERRAFORM_ENVIRONMENT:
    description: "Environment sur lequel deployer"
    required: true

  AZURE_TENANT_ID:
    required: true

  AZURE_SUBSCRIPTION_ID:
    required: true

runs:
  using: "composite"
  steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Deploy ${{ inputs.TERRAFORM_ENVIRONMENT }}
        env:
          TERRAFORM_ENVIRONMENT: ${{ inputs.TERRAFORM_ENVIRONMENT }}
          AZURE_TENANT_ID: ${{ inputs.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ inputs.AZURE_SUBSCRIPTION_ID }}
        shell: bash
        run: |
          cd .cd
          terraform init
          terraform plan -var="environment=${TERRAFORM_ENVIRONMENT}"
          # terraform apply -auto-approve
