name: "Terraform Deploy"
description: "Deploie application + service sur azure"

inputs:
  TERRAFORM_ENVIRONMENT:
    description: "Environment sur lequel deployer"
    required: true

  AZURE_CREDENTIALS:
    required: true

runs:
  using: "composite"
  steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ inputs.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Deploy ${{ inputs.TERRAFORM_ENVIRONMENT }} - Init
        shell: bash
        run: |
          cd .cd
          ls -la
          terraform init

      - name: Deploy ${{ inputs.TERRAFORM_ENVIRONMENT }} - Plan
        env:
          TERRAFORM_ENVIRONMENT: ${{ inputs.TERRAFORM_ENVIRONMENT }}
        shell: bash
        run: |
          cd .cd
          ls -la
          terraform plan -var="environment=${TERRAFORM_ENVIRONMENT}"

      - name: Deploy ${{ inputs.TERRAFORM_ENVIRONMENT }} - Apply
        shell: bash
        run: |
          cd .cd
          terraform apply -auto-approve
