name: "Setup Build Environment"
description: "Setup environment de build"

runs:
  using: "composite"
  steps:
    - name: Setup Environment
      shell: bash
      run: |
        # initialiser environment de developpement
        pip install -e .\[development\]

        # mettre les configurations du projet en variable d'environment
        source .ci/yaml_to_variables.sh configs/paths_config.yaml
