name: "Setup Build Environment"
description: "Setup environment de build"

runs:
  using: "composite"
  steps:
    - name: Setup Environment
      shell: bash
      run: |
        # initialiser environment
        pip install -e .\[development\]
