#
# Les noms de proprietes sont en majuscules
# pour respecter la convention de nomenclature 
# des variables d'environment
#
# les path sont relatifs au fichier lui-meme

!ffury.configs.PathsConfig

PROJECT_NAME: FeatheredFury

PYTHON_INTERPRETER: python3

CONFIGS_DIR: !relative_path .

BUILD_DIR: !relative_path ../build

DATA_DIR: !relative_path ../data

MODELS_DIR: !relative_path ../models

CI_DIR: !relative_path ../.ci
