!ffury.configs.PreprocessConfig

# split parameters -----
split_train_size: 0.6
split_test_size: 0.2
split_validation_size: 0.2

# audio preprocessing parameters -----

# audio resampling (implicitement mono)
clip_sampling_rate_hz: 22050

# audio clip split into segments
segment_size_ms: 3000
segment_overlap_size_ms: 1500
group_segment_count: 3
group_count: 1372

# audio segment tranformed into log mel spectrogram
spectrogram_stft_window_size_ms: 200
spectrogram_stft_frame_size_ms: 100
spectrogram_fmin: 500
spectrogram_fmax: 10000
spectrogram_n_mels: 128
