!ffury.configs.TrainConfig

model_factory: !ffury.keras_adapters.KerasDummyModelFactory {}

measurable: !ffury.keras_adapters.KerasMeasurable
  average: macro

trainable: !ffury.keras_adapters.KerasTrainable {}

parameters: !include train_parameters.yaml
