name: "Train"
description: "Genere modele"

inputs:
  NEPTUNE_API_TOKEN:
    description: "Token API Neptune"
    required: true

  BUILD_MACHINE:
    required: false
    default: None

runs:
  using: "composite"
  steps:
    - name: Indexer Donnees
      run: |
        ffury dataset index

    - name: Entrainement
      env:
        NEPTUNE_API_TOKEN: ${{ inputs.NEPTUNE_API_TOKEN }}
        BUILD_MACHINE: ${{ inputs.BUILD_MACHINE }}
      run: |
        ffury train
