name: Development Workflow
on:
  push:
    branches:
      - develop
jobs:
  GenerateModel:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Setup Environment
      #   run: |
      #     # initialiser environment de build
      #     pip install -r .ci/requirements-build.txt

      #     # mettre les configurations du projet en variable d'environment
      #     source .ci/yaml_to_variables.sh configs/paths_config.yaml

      - name: Init DVC Python
        run: |
          pip install dvc
          pip install dvc-gdrive

      - name: Update pyopenssl
        run: |
          echo "1 ++++++++++++++++++"
          pip list | grep SSL

          echo "3 ++++++++++++++++++"
          pip install pyopenssl --upgrade

          echo "4 ++++++++++++++++++"
          pip list | grep SSL


      - name: Obtenir les donnees
        env:
          GDRIVE_URL: ${{ secrets.GDRIVE_URL }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          # configurer DVC pour acceder Google Drive
          dvc remote add --default gdrive ${GDRIVE_URL}

          echo "A <------------"

          # authentication via Service Account - 
          dvc remote modify gdrive gdrive_use_service_account true

          echo "B <------------"

          dvc remote modify gdrive gdrive_acknowledge_abuse true

          echo "C <------------"

          dvc status -c

          # obtenir le data
          dvc pull

      # - name: Train Model
      #   env:
      #     NEPTUNE_PROJECT: ${{ secrets.NEPTUNE_PROJECT }}
      #     NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
      #   run: |
      #     dvc pull ${DATA_DIR}
