name: "Monitoring Production Metrics"

on:
  workflow_dispatch:
  schedule:
    # https://jasonet.co/posts/scheduled-actions/
    - cron: "* * * * *"

jobs:
  MetricMonitoring:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: "Setup Environment"
        uses: ./.github/actions/setup-monitoring-environment

      - name: Get Azure Infos
        uses: ./.github/actions/terraform-get-infos
        with:
          TERRAFORM_ENVIRONMENT: production
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Monitoring
        env:
          EVIDENTLY_API_TOKEN: ${{ secrets.EVIDENTLY_API_TOKEN }}
          EVIDENTLY_PROJECT_ID: ${{ secrets.EVIDENTLY_PROJECT_ID }}
        shell: bash
        run: |
          export AZURE_STORAGE_CONNECTION_STRING=$(cat ./build/storage_connection_string.txt)
          ffury monitoring drift-test
