name: "Monitoring Production Metrics"

on:
  schedule:
    # https://jasonet.co/posts/scheduled-actions/
    - cron: "* * * * *"

jobs:
  MetricMonitoring:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: "Setup Environment"
        uses: ./.github/actions/setup-build-environment

      - name: Get Azure Infos
        uses: ./.github/actions/terraform-get-infos
        with:
          TERRAFORM_ENVIRONMENT: production
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Monitoring
        run: |
          value=$(cat ./build/storage_connection_string.txt)
          export AZURE_STORAGE_CONNECTION_STRING="${value}"

          cat ./build/storage_connection_string.txt
          getenv | grep AZ

          ffury monitoring drift-test
