name: "Production Metric Monitoring"

on:
  schedule:
    # https://jasonet.co/posts/scheduled-actions/
    - cron: ${{vars.MONITORING_CRON_FREQEUNCY}}

jobs:
  MetricMonitoring:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: "Setup Environment"
        uses: ./.github/actions/setup-build-environment

      - name: Get Azure Infos
        uses: ./.github/actions/terraform-get-infos
        with:
          TERRAFORM_ENVIRONMENT: production
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Monitoring
        run: |
          cat ./build/web_app_url.txt
          cat ./build/storage_connection_string.txt
