name: "Production Workflow"

on:
  push:
    branches:
      - main

jobs:
  ProductionDeployment:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Environment
        uses: ./.github/actions/setup-build-environment

      - name: Deploy Production
        uses: ./.github/actions/terraform-deploy
        with:
          TERRAFORM_ENVIRONMENT: production
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
