name: "Staging Workflow"

on:
  push:
    branches:
      - staging

jobs:
  StagingDeployment:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Environment
        uses: ./.github/actions/setup-build-environment

      - name: Synchroniser Modele
        uses: ./.github/actions/neptune-sync-model
        with:
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
          NEPTUNE_TAG: ${{ secrets.NEPTUNE_TAG }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Deploy Staging
        uses: ./.github/actions/terraform-deploy
        with:
          AZURE_ENVIRONMENT: staging
