name: "Staging Workflow"

on:
  push:
    branches:
      - main

jobs:
  Deployment:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # - name: Setup Environment
      #   uses: ./.github/actions/setup-build-environment

      - name: Check folders
        shell: bash
        run: |
          pwd
          cd ./.github/actions/neptune-sync-model
          pwd
          ls -la .

      - name: "Synchroniser Modele"
        uses: ./.github/actions/neptune-sync-model
        with:
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
          NEPTUNE_TAG: ${{ secrets.NEPTUNE_TAG }}

      - name: Test Sync
        shell: bash
        run: |
          ls -la ./models
          echo "Ici"


      # - name: Deploy Staging
      #   env:
      #     AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      #   run: |
      #     # fetcher le modele de neptune ai
      #     cd .cd
      #     terraform init
      #     terraform apply -var="environment=staging" -auto-approve
