name: "Staging Workflow"

on:
  push:
    branches:
      - staging

jobs:
  StagingDeployment:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Environment
        uses: ./.github/actions/setup-build-environment

      - name: Synchroniser Donnees
        uses: ./.github/actions/dvc-sync
        with:
          GDRIVE_URL: ${{ secrets.GDRIVE_URL }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

      - name: Synchroniser Modele
        uses: ./.github/actions/neptune-sync-model
        with:
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
          NEPTUNE_TAG: staging_latest

      - name: Deploy Staging
        uses: ./.github/actions/terraform-deploy
        with:
          TERRAFORM_ENVIRONMENT: staging
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
